remove BufferedInputStream, it conflicts with AutoCloseOutputStream
When using a BufferedInputStream with AutoCloseOutputStream, something
closes the stream too early, causing this stacktrace:

java.io.IOException: write failed: EPIPE (Broken pipe)
    at libcore.io.IoBridge.write(IoBridge.java:462)
    at java.io.FileOutputStream.write(FileOutputStream.java:187)
    at info.guardianproject.iocipherexample.IOCipherContentProvider$PipeFeederThread.run(IOCipherContentProvider.java:102)
Caused by: libcore.io.ErrnoException: write failed: EPIPE (Broken pipe)
    at libcore.io.Posix.writeBytes(Native Method)
    at libcore.io.Posix.write(Posix.java:187)
    at libcore.io.BlockGuardOs.write(BlockGuardOs.java:197)
    at libcore.io.IoBridge.write(IoBridge.java:457)
    ... 2 more